### PR TITLE
Remove kio message and better api url handling

### LINKED ISSUE #50: Change Kio message in the end of deploy
We should remove or change the Kio message in the end of the deploy. Currently it shows:

```
You can approve this new version using the command:

	$ kio version approve lizzy v1
```

Which lead to think the new version was registered already in Kio, but [that changed in the release2.0](https://github.com/zalando/lizzy/issues/120)

### LINKED ISSUE #52: Better handling when LIZZY_URL is wrong
Probably this issue https://github.com/zalando/lizzy/issues/135 should apply more to the client than the Lizzy agent.

----------

When using Lizzy we pass the LIZZY_URL to the lizzy-client command line. If we put the wrong url, like https://lizzy-instance.example.com/ instead of https://lizzy-instance.example.com/api we get a "504 Gateway Timeout" error from the load balancer.

There should be a more user-friendly way to handle better that case.

### PR DESCRIPTION
**Pull request by jmcs**
Fixes #50.
Fixes #52.

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
We should not remove kio code yet. I did that in this PR https://github.com/zalando/lizzy-client/pull/51 and closed it later. The thing is that users are expecting that to happen (registering versions in kio).

**Comment by rafaelcaricio** [comment]
Instead we should move the kio versions create from the server to client.

**Comment by jmcs** [comment]
@rafaelcaricio I agree but that should be another issue. I'll create it now.

**Comment by rafaelcaricio** [comment]
👍

**Pull request merged**
